libs/cgse-common/src/egse/config.py, libs/cgse-common/src/egse/env.py, libs/cgse-common/src/egse/settings.py
The environment variables still had "PLATO_" in their names.  I have replaced those by a more generic name.
#10 
None.  It is only a matter of exporting the environment variables with the correct names.
After the changes to the code and exporting the required environment variables, I have tried to start each of the core services, with success.
=> Use generic environment variables

libs/cgse-common/src/egse/env.py, libs/cgse-common/src/egse/setup.py
Before:
```
$ uv run py -m egse.setup --use-cm
NavigableDict
├── site_id: HOME
├── history
│   └── 0: Initial zero Setup for HOME
├── Setup ID: 00000
└── Loaded from: /Users/rik/data/HOME/conf/SETUP_HOME_00000_240123_120000.yaml
```
now it shows:
```
$ uv run py -m egse.setup --use-cm
Setup
├── site_id: HOME
├── history
│   └── 0: Initial zero Setup for HOME
├── Setup ID: 00000
└── Loaded from: /Users/rik/data/HOME/conf/SETUP_HOME_00000_240123_120000.yaml
```
=> Setup now identifies as a Setup instead of a NavigabelDict

docs/dev_guide/plugins.md, mkdocs.yml
Added a page to document how to add plugin for the CGSE.
=> 🚧 – documentation for plugins

libs/cgse-common/src/egse/setup.py, libs/cgse-core/src/egse/confman/__init__.py, libs/cgse-core/src/egse/confman/confman_cs.py
The Setup filename was not properly parsed to extract the site_id and the setup_id when the site_id contains an underscore. This lead to an error when asking the list of Setups. In addition, the Failure that was returned was not handled on the client side.
=> fixes a bug parsing the Setup filename when the site id contains an underscore

libs/cgse-common/pyproject.toml, libs/cgse-coordinates/pyproject.toml, libs/cgse-core/pyproject.toml, libs/cgse-core/src/egse/confman/confman_cs.py, libs/cgse-core/src/egse/logger/log_cs.py, libs/cgse-core/src/egse/procman/procman_cs.py, libs/cgse-core/src/egse/storage/storage_cs.py, libs/cgse-core/src/scripts/_status.py, libs/cgse-gui/pyproject.toml, projects/generic/cgse-tools/pyproject.toml, projects/generic/keithley-tempcontrol/pyproject.toml, projects/generic/symetrie-hexapod/pyproject.toml, projects/plato/plato-fits/pyproject.toml, projects/plato/plato-hdf5/pyproject.toml, projects/plato/plato-spw/pyproject.toml, pyproject.toml
- The `log_cs` and `sm_cs` have been converted to Typer apps
- small editorial fixes
- Bumped patch version 0.2.3 → 0.2.4
=> Convert core services to Typer apps

docs/libs/cgse-common/settings.md
The folder that contains the settings.yaml file which will be loaded by an entry-point, shall be a proper python module, i.e. it shall contain a `__init__.py` file.
=> added a warning for a plugin loading

libs/cgse-common/src/egse/setup.py
I always thought the private_attribute `_filename` was a string, but it actually a Path. So, make sure it's always a Path.
=> private attribute _filename shall be a Path

docs/api/bits.md, docs/api/calibration.md, docs/api/command.md, docs/api/config.md, docs/api/control.md, docs/api/counter.md, docs/api/decorators.md, docs/api/device.md, docs/api/dict.md, docs/api/dicts.md, docs/api/dummy.md, docs/api/exceptions.md, docs/api/settings.md, docs/api/system.md, libs/cgse-common/src/egse/bits.py, libs/cgse-common/src/egse/calibration.py, libs/cgse-common/src/egse/command.py, libs/cgse-common/src/egse/config.py, libs/cgse-common/src/egse/control.py, libs/cgse-common/src/egse/counter.py, libs/cgse-common/src/egse/decorators.py, libs/cgse-common/src/egse/device.py, libs/cgse-common/src/egse/dicts.py, libs/cgse-common/src/egse/dummy.py, libs/cgse-common/src/egse/protocol.py, libs/cgse-common/src/egse/proxy.py, libs/cgse-common/src/egse/setup.py, libs/cgse-common/src/egse/system.py, libs/cgse-common/tests/test_setup.py, mkdocs.yml
Generating the API documentation generated a lot of warnings about arguments and return types. These have now been fixed.
The unit tests for `cgse-common` still result in all green.
=> fixed argument and return types for a lot of functions and methods

libs/cgse-common/noxfile.py, libs/cgse-common/pyproject.toml, libs/cgse-common/src/egse/decorators.py, libs/cgse-common/src/egse/dummy.py, libs/cgse-common/src/egse/zmq_ser.py, libs/cgse-coordinates/pyproject.toml, projects/plato/plato-fits/pyproject.toml, projects/plato/plato-spw/pyproject.toml
- 'nox' is now used to run unit tests for different Python environments
- `pyproject.toml` adapted to fix dependencies for Python 3.9, 3.10, 3.11, and 3.12
- added some type hints
=> Introduced 'nox' to test different Python environments

libs/cgse-common/noxfile.py, libs/cgse-common/pyproject.toml, libs/cgse-common/src/egse/control.py, libs/cgse-common/src/egse/plugin.py, libs/cgse-common/src/egse/process.py, libs/cgse-common/src/egse/settings.py, libs/cgse-common/tests/scripts/handle_sigterm.py, libs/cgse-common/tests/test_process.py, pyproject.toml
This pull request fixes some issues with testing the cgse-common for different python environments using `nox`.
- The `entrypoints()` in `importlib.metadata` had a breaking change in 3.12+
- The `nox` now has a session to run unit tests using `uv` and another session to use `standard pip`
- The `pyproject.toml` now has conditional dependencies for Python versions 3.9 and 3.10+
- The `egse.plugin` now handles he `entry points` fix
- some editorial and type hint changes
=> Fix python 3.12+ backward incompatible changes

libs/cgse-common/src/egse/bits.py, libs/cgse-common/src/egse/command.py, libs/cgse-common/src/egse/dummy.py, libs/cgse-common/src/egse/monitoring.py, libs/cgse-common/src/egse/protocol.py, libs/cgse-common/src/egse/services.py, libs/cgse-common/tests/test_bits.py, libs/cgse-common/tests/test_process.py, libs/cgse-common/tests/test_protocol.py, libs/cgse-core/src/egse/confman/__init__.py, libs/cgse-core/src/egse/procman/__init__.py, libs/cgse-core/src/egse/storage/__init__.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/joran_protocol.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/puna_protocol.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/zonda_protocol.py
First round of refactoring for CommandProtocol.
- CommandProtocol now inherits from BaseCommandProtocol
- Improve typing hints
- control_server is now a mandatory argument on the base class
- extract methods into the base class
- simple initial unit test
- deprecated get_function() and get_method() in egse.command, use the functions in egse.protocol
=> Refactoring of protocol

libs/cgse-common/src/egse/decorators.py, libs/cgse-common/src/egse/system.py, libs/cgse-common/src/egse/zmq_ser.py, libs/cgse-common/tests/test_decorators.py, libs/cgse-core/pyproject.toml, libs/cgse-core/src/cgse_core/_start.py, libs/cgse-core/src/cgse_core/_status.py, libs/cgse-core/src/cgse_core/_stop.py, libs/cgse-core/src/cgse_core/cgse_explore.py, libs/cgse-core/src/cgse_core/services.py, libs/cgse-core/src/egse/logger/log_cs.py, libs/cgse-core/src/egse/registry/__init__.py, libs/cgse-core/src/egse/registry/backend.py, libs/cgse-core/src/egse/registry/client.py, libs/cgse-core/src/egse/registry/server.py, libs/cgse-core/src/egse/registry/service.py, libs/cgse-core/tests/script_test_async_registry_client.py, libs/cgse-core/tests/script_test_service_registry_server.py, libs/cgse-core/tests/script_test_sync_registry_client.py, libs/cgse-core/tests/services.py, libs/cgse-core/tests/test_registry_backend.py, libs/cgse-core/tests/test_registry_service.py, libs/cgse-core/tests/test_server_running.py, libs/cgse-core/tests/test_server_running_with_fixture.py, libs/cgse-core/tests/test_zmq_microservice.py
The main functionality added is the registry service which is part of the core services. The idea is that this registry serves as a service point for all core services and device servers. Any of these processes registers to the service registry with information about their status, hostname, port numbers, and metadata. The service registry will keep track of the health of the registered services by monitoring their heartbeat. When a process or script needs a service, it will request the information it needs to contact the service from the service registry. 
Two backend options have been implemented, an *AsyncInMemoryBackend* and a *AsyncSQLiteBackend*, both implement the *AsyncRegistryBackend* protocol. The former is mainly for test purposes, the latter will be used in production.
Summary …
=> add registry services to the core services functionality

libs/cgse-common/noxfile.py, libs/cgse-common/pyproject.toml, libs/cgse-common/src/egse/exceptions.py, libs/cgse-common/src/egse/system.py, libs/cgse-common/src/egse/zmq_ser.py, libs/cgse-coordinates/pyproject.toml, libs/cgse-core/pyproject.toml, libs/cgse-core/src/cgse_core/_status.py, libs/cgse-core/src/cgse_core/services.py, libs/cgse-core/src/egse/registry/client.py, libs/cgse-gui/pyproject.toml, projects/generic/cgse-tools/pyproject.toml, projects/generic/keithley-tempcontrol/pyproject.toml, projects/generic/symetrie-hexapod/pyproject.toml, projects/plato/plato-fits/pyproject.toml, projects/plato/plato-hdf5/pyproject.toml, projects/plato/plato-spw/pyproject.toml, pyproject.toml
- added InitialisationError
- editorial changes and added two functions: `get_current_location` and `log_rich_output`
- added some convenience functions to create requests and responses.
- disable py_tests, use uv_tests by default
- added pytest-asyncio
- added connect/disconnect and context manager functions, optional timeout for _send_request
- added logging
- fixed status report for service registry
- bump 0.7.0 -> 0.7.1
=> maintenance service registry

libs/cgse-core/src/egse/registry/client.py, libs/cgse-core/src/egse/registry/service.py, libs/cgse-core/tests/script_test_async_registry_client.py, libs/cgse-core/tests/script_test_sync_registry_client.py
Improved the synchronous RegistryClient:
- added connect() and disconnect() methods
- can now be used as a context manager
Also unit tests are fixed.
=> improve synchronous  RegistryClient

libs/cgse-common/pyproject.toml, libs/cgse-common/src/egse/dummy.py, libs/cgse-common/src/egse/protocol.py, libs/cgse-core/src/egse/confman/__init__.py, libs/cgse-core/src/egse/procman/__init__.py
- Added the dependency `influxdb3-python` to the `pyproject.toml` file for `cgse-common`.  For now, I have not removed the `prometheus-client` dependency, as not all processes have their metrics migrated to InfluxDB3.  This will be done at a later stage.
- Upon initialisation of a `CommandProtocol`, I now create an `InfluxDB3Client`, which is used in the device protocol to add metrics to the InfluxDB database.
- For the Configuration Manager, the metrics are now added to InfluxDB rather than Prometheus.
#108 
Tested on my own laptop with the following configuration:
- InfluxDB3 Core installed and running locally;
- Grafana installed and running locally;
- CGSE core services running;
- Created a Grafana dashboard, showing, e.g., `CM_SETUP_ID`.
- Table `CM_CS` created in the project …
=> Started migration to InfluxDB3

libs/cgse-common/src/egse/dummy.py, libs/cgse-common/src/egse/protocol.py, libs/cgse-core/src/egse/confman/__init__.py, libs/cgse-core/src/egse/procman/__init__.py, projects/generic/keithley-tempcontrol/src/egse/tempcontrol/keithley/daq6510_protocol.py
- Missing environment variables `PROJECT` and/or `INFLUXDB3_AUTH_TOKEN`:
- Log warning message;
- `self.client` will be `None`;
- Check for this when writing metrics to InfluxDB (in the `get_housekeeping` method in the device protocols);
- Check for this when calling the `quit` method of the device protocol (when the CS is stopped);
- InfluxDB not running:
- Log warning message;
- Device protocol automatically picks up on a (re-)start of InfluxDB.
#108 
None
See #109 and #111.
=> Handle potential problems with the connection to InfluxDB 

libs/cgse-common/src/egse/control.py, libs/cgse-common/src/egse/dummy.py, libs/cgse-common/src/egse/protocol.py, libs/cgse-core/src/egse/confman/__init__.py, libs/cgse-core/src/egse/procman/__init__.py
In the `serve` method of the `ControlServer` class, in the section where we store the HK information to a dedicated CSV file, we call a new method, `propagate_metrics`, which propagates the HK to InfluxDB.  That way, everything metrics-related has been moved out of the device protocols, which is cleaner and avoids double work.
#108 
None
Tested in a similar fashion as in #109, #111, and #113.
=> Metrics populated (generically) from `ControlServer` instead of device protocols

bump.py, libs/cgse-common/src/egse/control.py, libs/cgse-common/src/egse/proxy.py, libs/cgse-common/src/egse/system.py, libs/cgse-common/src/scripts/cgse.py, libs/cgse-core/pyproject.toml, libs/cgse-core/src/cgse_core/services.py, libs/cgse-core/src/egse/registry/client.py
This is a maintenance pull request with changes to cgse-common and cgse-core that were needed to better support the development of device drivers.
- `egse.system` – added a method to check if a package is installed: `is_package_installed(<package name>)`
- `egse.control` – ControlServer now has two new methods `register_service()` and `deregister_service()` that need to be used by the sub-classes to register itself to the service registry.
- a new command `uv run cgse registry show-services` can be used to check which services exist and retrieve information about it
```
➜ uv run cgse registry show-services
[
{
'id': 'PunaControlServer-1411b612-6797-4735-8413-c0b9b2a76841',
'name': 'PunaControlServer',
'host': '192.168.68.70',
'port': 52147,
'metadata': {'service_port': 52145, …
```
=> core and common features to support service registration etc

projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/__init__.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/hexapod.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/puna.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/puna_cs.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/puna_protocol.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/punaplus.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/zonda.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/zonda_cs.py, projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/zonda_protocol.py, projects/generic/symetrie-hexapod/src/symetrie_hexapod/settings.yaml
- The `PunaProxy` can now be started as:
- `PunaProxy(protocol, hostname, port)
- `PunaProxy.from_identifier("PUNA_02")`
- `ZondaProxy` and `PunaPlusProxy` now also can be instantiated (factory created) with a `from_identifier()` class method.
- created a HexapodSimulator from which PUNA and ZONDA inherit
- in `settings.yaml` the group `PMAC Controller` has been replaced with `Hexapod Controller` (in local settings) and the PUNA and ZONDA Control Server groups are now one `Hexapod Control Server` group
- Puna and Zonda stop and status commands now consult the service registry
=> hexapods now work with services

libs/cgse-core/src/egse/registry/client.py
When the service registry is not responding, a timeout message was printed which wrongly mentioned 'ms' instead of 's'. This has been corrected.
=> corrected timeout message, now print 's' instead of 'ms'

libs/cgse-core/src/cgse_core/_status.py, libs/cgse-core/src/cgse_core/services.py
When a service is down, the `cgse core status` will print correctly that the service is not active, but it also prints the error log coming from the server.
```
Configuration Manager Status: not active
2025-05-26 11:39:28,930:         MainProcess: WARNING:egse.registry            :  258:client.py           :Service discovery failed: No healthy service of type CM_CS found
```
That information is only useful when debugging, so we will suppress it by default and you can use the `--no-suppress-errors` switch to show these error messages.
=> suppress errors when running a status command

libs/cgse-common/src/egse/config.py, libs/cgse-common/src/egse/resource.py, libs/cgse-common/tests/data/COPYING, libs/cgse-common/tests/test_config.py, libs/cgse-common/tests/test_process.py, libs/cgse-common/tests/test_resource.py, libs/cgse-gui/src/egse/gui/switch.py
- in following functions in `egse.config` shall require the `root` argument instead of making it optional:
- `find_dir` and `find_dirs` 
- `find_file` and `find_files`
- `find_first_occurrence_of_dir`
- `get_resource_dirs` and `get_resource_path` ⚠️ ‼️ these function were defined in both `egse/config.py` and `egse/resource.py`
- the `get_common_egse_root()` function shall be removed
Unit tests for `test_config.py` and `test_resource.py` have been updated accordingly.
=> fix optional root argument in config and resource and remove get_common_egse_root

libs/cgse-common/src/egse/config.py, libs/cgse-common/src/egse/resource.py, libs/cgse-common/src/egse/system.py, libs/cgse-common/tests/data/COPYING, libs/cgse-common/tests/test_config.py, libs/cgse-common/tests/test_process.py, libs/cgse-common/tests/test_resource.py, libs/cgse-core/src/egse/logger/__init__.py, libs/cgse-core/src/egse/logger/log_cs.py, libs/cgse-core/src/egse/registry/__init__.py, libs/cgse-core/src/egse/registry/backend.py, libs/cgse-core/src/egse/registry/client.py, libs/cgse-core/src/egse/registry/server.py, libs/cgse-core/tests/script_test_registry_client_server.py, libs/cgse-core/tests/test_registry_service.py, libs/cgse-gui/src/egse/gui/switch.py
The service registry had some problems with heartbeats and needed some refactoring. 
- the main problem was that the heartbeats intervened with the normal service requests for the asyncio clients, so the heartbeat is now sent to a different port then the normal requests. The server is adapted to listen to the heartbeat specific port.
- heartbeats were not properly sent in the sync server because the function that sends out the heartbeats is running in a separate thread. We had to adapt the `do_every` function in `egse.system` in order to allow the creation of the heartbeat socket in the thread.
- when the `do_every` function is running in a thread, it can now be stopped by using a `stop_event`
- added the function `get_logging_level(..)` to `egse.system`
- extracted the function …
=> Refactor service registry

libs/cgse-common/src/egse/control.py, libs/cgse-common/src/egse/proxy.py, libs/cgse-common/src/egse/services.py, libs/cgse-common/src/egse/system.py, libs/cgse-core/src/cgse_core/services.py, libs/cgse-core/src/egse/confman/__init__.py, libs/cgse-core/src/egse/confman/confman_cs.py, libs/cgse-core/src/egse/logger/__init__.py, libs/cgse-core/src/egse/procman/procman_cs.py, libs/cgse-core/src/egse/registry/client.py, libs/cgse-core/src/egse/storage/__init__.py, libs/cgse-core/src/egse/storage/storage_cs.py
The core services are not terminated timely when using the command `cgse core stop`. This has several reasons which are fixed in this pull request:
- The ServiceProxy was not yet adapted to the dynamic port allocation. This proxy is mainly used to send the `quit_server()` service command which could not reach the server because the endpoints were obviously wrong
- The `stop_heartbeat()` would work properly because  it used an event to stop the thread, but the sleep time in the thread loop was about 10s. So, by the time the thread was ended, other services would have been terminated or were also hanging for the same reason. This thread loop is executed in the `do_every()` function and we replaced the `time.sleep()` with a `stop_event.wait()` function. This function properly reacts …
=> fix termination of core services

libs/cgse-common/src/egse/process.py, libs/cgse-core/src/cgse_core/cgse_explore.py, projects/generic/cgse-tools/src/cgse_tools/cgse_commands.py, projects/generic/keithley-tempcontrol/src/keithley_tempcontrol/cgse_explore.py, projects/generic/lakeshore-tempcontrol/src/lakeshore_tempcontrol/cgse_explore.py
The `cgse show process` command will now display a rich table with processes:
To make this work, the interface of `show_processes()` changed. It should now return a list of ProcessInfo dataclasses.
=> improve `cgse show procs` command

libs/cgse-common/src/egse/setup.py, libs/cgse-common/src/egse/state.py, libs/cgse-coordinates/src/egse/coordinates/__init__.py, libs/cgse-coordinates/src/egse/coordinates/avoidance.py, libs/cgse-core/src/egse/confman/__init__.py, projects/plato/plato-spw/src/egse/spw.py
This pull request fixes the problem of GlobalState.setup to automatically load the Setup from the configuration manager. That function is for the `load_setup()` method instead. `GlobalState.setup` is a property that now returns the current Setup in the process or None when no Setup was previously loaded.
=> fix GlobalState.setup

libs/cgse-common/pyproject.toml, libs/cgse-common/src/cgse_common/cgse.py, libs/cgse-coordinates/pyproject.toml, libs/cgse-core/pyproject.toml, libs/cgse-core/src/cgse_core/services.py, libs/cgse-core/src/cgse_core/settings.yaml, libs/cgse-core/src/egse/confman/__init__.py, libs/cgse-core/src/egse/confman/confman_cs.py, libs/cgse-core/src/egse/control.py, libs/cgse-core/src/egse/logger/log_cs.py, libs/cgse-core/src/egse/monitoring.py, libs/cgse-core/src/egse/procman/__init__.py, libs/cgse-core/src/egse/procman/procman_cs.py, libs/cgse-core/src/egse/protocol.py, libs/cgse-core/src/egse/storage/__init__.py, libs/cgse-core/src/egse/storage/storage_cs.py, libs/cgse-gui/pyproject.toml, projects/generic/cgse-tools/pyproject.toml, projects/generic/keithley-tempcontrol/pyproject.toml, projects/generic/lakeshore-tempcontrol/pyproject.toml, projects/generic/symetrie-hexapod/pyproject.toml, projects/plato/plato-fits/pyproject.toml, projects/plato/plato-hdf5/pyproject.toml, projects/plato/plato-spw/pyproject.toml, pyproject.toml
This is a maintenance pull request which handles a numbers of hanging issues:
- fixed port numbers for core services until the registration problem is resolved
- proxies now handle fixed port numbers of the core services properly
- renamed cgse commands 
- registry → reg
- notify → not
- proper sorting of the `reg` and `not` commands
- bumped minor version → 0.16.0
=> fixed port numbers core services

libs/cgse-common/pyproject.toml, libs/cgse-coordinates/pyproject.toml, libs/cgse-core/pyproject.toml, libs/cgse-core/src/cgse_core/settings.yaml, libs/cgse-core/src/egse/confman/__init__.py, libs/cgse-core/src/egse/dummy.py, libs/cgse-core/src/egse/logger/__init__.py, libs/cgse-core/src/egse/notifyhub/__init__.py, libs/cgse-core/src/egse/notifyhub/server.py, libs/cgse-core/src/egse/procman/__init__.py, libs/cgse-core/src/egse/registry/__init__.py, libs/cgse-core/src/egse/storage/__init__.py, libs/cgse-gui/pyproject.toml, projects/generic/cgse-tools/pyproject.toml, projects/generic/keithley-tempcontrol/pyproject.toml, projects/generic/lakeshore-tempcontrol/pyproject.toml, projects/generic/symetrie-hexapod/pyproject.toml, projects/plato/plato-fits/pyproject.toml, projects/plato/plato-hdf5/pyproject.toml, projects/plato/plato-spw/pyproject.toml, pyproject.toml
This is a maintenance pull request that adds consistency to the Proxy subclasses.
- use get_endpoint() function
- define constants from settings with proper defaults
- when port = 0 use service registry
- the settings file for the core services has been cleaned up and all core services now have fixed port numbers.
Version bump to 0.16.1.
=> use get endpoint

libs/cgse-common/pyproject.toml, libs/cgse-common/src/egse/env.py, libs/cgse-common/src/egse/system.py, libs/cgse-coordinates/pyproject.toml, libs/cgse-core/pyproject.toml, libs/cgse-core/src/cgse_core/_start.py, libs/cgse-core/src/cgse_core/_stop.py, libs/cgse-gui/pyproject.toml, projects/generic/cgse-tools/pyproject.toml, projects/generic/keithley-tempcontrol/pyproject.toml, projects/generic/lakeshore-tempcontrol/pyproject.toml, projects/generic/lakeshore-tempcontrol/src/lakeshore_tempcontrol/cgse_services.py, projects/generic/symetrie-hexapod/pyproject.toml, projects/generic/symetrie-hexapod/src/symetrie_hexapod/cgse_services.py, projects/plato/plato-fits/pyproject.toml, projects/plato/plato-hdf5/pyproject.toml, projects/plato/plato-spw/pyproject.toml, pyproject.toml
The start and stop scripts of core services and control servers now redirect their output no longer to the users home folder, but to the log location.
=> redirect output to log location

libs/cgse-common/pyproject.toml, libs/cgse-common/src/egse/signal.py, libs/cgse-common/tests/test_influxdb_plugin.py, libs/cgse-common/tests/test_metrics.py, libs/cgse-coordinates/pyproject.toml, libs/cgse-core/pyproject.toml, libs/cgse-core/src/egse/confman/__init__.py, libs/cgse-core/src/egse/dummy.py, libs/cgse-core/src/egse/notifyhub/services.py, libs/cgse-core/src/egse/procman/__init__.py, libs/cgse-core/src/egse/proxy.py, libs/cgse-core/src/egse/services.py, libs/cgse-core/src/egse/storage/__init__.py, libs/cgse-core/tests/script_test_registry_client_server.py, libs/cgse-core/tests/script_test_service_registry_server.py, libs/cgse-gui/pyproject.toml, projects/generic/cgse-tools/pyproject.toml, projects/generic/keithley-tempcontrol/pyproject.toml, projects/generic/lakeshore-tempcontrol/pyproject.toml, projects/generic/symetrie-hexapod/pyproject.toml, projects/plato/plato-fits/pyproject.toml, projects/plato/plato-hdf5/pyproject.toml, projects/plato/plato-spw/pyproject.toml, pyproject.toml
This pull request fixes the timeout argument for Proxy subclasses. The timeout should be in seconds instead of milliseconds.
Closes #171
=> Fix timeouts in proxy

libs/cgse-common/pyproject.toml, libs/cgse-coordinates/pyproject.toml, libs/cgse-core/pyproject.toml, libs/cgse-core/src/egse/control.py, libs/cgse-core/src/egse/logger/log_cs.py, libs/cgse-core/src/egse/registry/client.py, libs/cgse-core/src/egse/registry/server.py, libs/cgse-gui/pyproject.toml, projects/generic/cgse-tools/pyproject.toml, projects/generic/keithley-tempcontrol/pyproject.toml, projects/generic/lakeshore-tempcontrol/pyproject.toml, projects/generic/symetrie-hexapod/pyproject.toml, projects/plato/plato-fits/pyproject.toml, projects/plato/plato-hdf5/pyproject.toml, projects/plato/plato-spw/pyproject.toml, pyproject.toml
This pull request fixes the re-registration problem.
- When a control server goes to sleep or is stopped (not killed) it will automatically re-register to the service registry when is returns from sleep or continues after being stopped.
- The periodic heartbeat is stopped and restarted
- The registration gets another service_id.
This was tested by 
- bringing the macBook laptop to sleep by closing its lid and reopening after one minute
- using the `kill -STOP <PID>` and `kill -CONT <PID>` commands on the control server
- also bringing back up the process before it was registered restored the registration properly
=> Fix re-registration problem

libs/cgse-common/pyproject.toml, libs/cgse-coordinates/pyproject.toml, libs/cgse-core/pyproject.toml, libs/cgse-core/src/egse/proxy.py, libs/cgse-core/src/egse/registry/client.py, libs/cgse-core/src/egse/registry/server.py, libs/cgse-gui/pyproject.toml, projects/generic/cgse-tools/pyproject.toml, projects/generic/keithley-tempcontrol/pyproject.toml, projects/generic/lakeshore-tempcontrol/pyproject.toml, projects/generic/symetrie-hexapod/pyproject.toml, projects/plato/plato-fits/pyproject.toml, projects/plato/plato-hdf5/pyproject.toml, projects/plato/plato-spw/pyproject.toml, pyproject.toml
This pull request fixes the re-registration strategy for asynchronous registry clients.
Additionally:
- put some logging statements under a VERBOSE_DEBUG clause
- report heartbeat port for service registry server
=> fix async registry client for re-registration
