- NOTES.md
Added some info in the NOTES file.
> added info on get_common_egse_root and projects

- projects/plato/plato-hdf5/pyproject-setuptools.toml
- projects/plato/plato-hdf5/pyproject.toml
making `pyproject.toml` Poetry compatible.
> converted pyproject.toml from setuptools to Poetry for plato-hdf5

- libs/cgse-common/src/egse/calibration.py
- Mostly adopted from the plato-common-egse repository;
- For the Cernox sensors, I have added the Chebychev calibration.
> Temperature sensor calibration

- libs/cgse-common/pyproject.toml
- libs/cgse-common/src/egse/command.py
- libs/cgse-common/src/egse/env.py
- libs/cgse-common/src/egse/hk.py
- libs/cgse-common/src/egse/setup.py
- libs/cgse-common/tests/conftest.py
- libs/cgse-common/tests/data/LAB23/README.md
- libs/cgse-common/tests/data/common/telemetry/tm-dictionary-default.csv
- libs/cgse-common/tests/test_env.py
- libs/cgse-common/tests/test_hk.py
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
- Improvements to `egse.env.py` and `egse.hk.py`.
- initial unit test added for `get_housekeeping()`
> 🚧 - improvements to env and hk

- docs/dev_guide/uv.md
- mkdocs.yml
This is just a small addition to the `uv.md` doc file.
> add an info section to uv

- docs/dev_guide/plugins.md
- docs/package_list.md
- added description for the `cgse.explore` entry-point
- added table with known external packages that work with CGSE
> updates to plugins.md and package_list.md

- libs/cgse-common/pyproject.toml
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
Packages have also been published on PyPI.
> bumped version to 0.3.0

- libs/cgse-common/pyproject.toml
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-coordinates/src/cgse_coordinates/settings.yaml
- libs/cgse-coordinates/src/egse/coordinates/__init__.py
- libs/cgse-coordinates/src/egse/coordinates/avoidance.py
- libs/cgse-coordinates/src/egse/coordinates/cslmodel.py
- libs/cgse-coordinates/src/egse/coordinates/laser_tracker_to_dict.py
- libs/cgse-coordinates/src/egse/coordinates/pyplot.py
- libs/cgse-coordinates/tests/test_avoidance.py
- libs/cgse-coordinates/tests/test_coordinates_plot.py
- libs/cgse-coordinates/tests/test_coordinates_serialize.py
- libs/cgse-coordinates/tests/test_point.py
- libs/cgse-coordinates/tests/test_reference_frames.py
- libs/cgse-coordinates/tests/test_refmodel.py
- libs/cgse-core/pyproject.toml
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
This fixes the code in cgse-coordinates and added unit tests. It's a work in progress, we would like to get full coverage for this package.
> 🚧 – Fix cgse coordinates

- docs/dev_guide/index.md
- docs/dev_guide/uv.md
- docs/package_list.md
Some updates on the development guide and the uv workflow.
> documentation update

- libs/cgse-common/src/egse/resource.py
- libs/cgse-common/tests/test_resource.py
The unit tests of egse.resource failed and have been fixed and improved.
> fix egse.resources

- libs/cgse-common/pyproject.toml
- libs/cgse-common/src/egse/randomwalk.py
- libs/cgse-common/src/scripts/cgse.py
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
- The `cgse` command was previously defined in `cgse-core`. We have now moved this into `cgse-common`.
- The is a RandomWalk module added, but it is currently unused. The module is intended for unit tests to provide input data.
- bumped version to 0.5.0
> move main cgse command into cgse-common and bump version

- docs/projects/symetrie-hexapod.md
- libs/cgse-coordinates/src/egse/coordinates/referenceFrame.py
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/__init__.py
- projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/puna_cs.py
- projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/puna_protocol.py
- projects/generic/symetrie-hexapod/src/symetrie_hexapod/cgse_services.py
- projects/generic/symetrie-hexapod/src/symetrie_hexapod/settings.yaml
- projects/generic/symetrie-hexapod/tests/test_puna.py
- projects/generic/symetrie-hexapod/tests/test_puna_simulator.py
Initial fixes to the Hexapod PUNA:
- `pyproject.toml` file adapted
- start, stop, status service commands have been implemented
- added settings.yaml file
- debugging messages of reference frames can be disabled with global DEBUG flag
- unit tests added and working for the simulator
> hexapod puna fixed and unit tests added

- README.md
- docs/dev_guide/coding_style.md
- docs/dev_guide/installation.md
- docs/dev_guide/uv.md
- docs/dev_guide/versioning.md
- docs/getting_started.md
- docs/initialize.md
- docs/roadmap.md
- mkdocs.yml
- added a roadmap
- added an explanation on version numbers
- updated several developer guides
- updated getting started and initialisation guides
> a big documentation update

- docs/dev_guide/docs.md
- docs/dev_guide/monorepo.md
- mkdocs.yml
- projects/generic/cgse-tools/pyproject.toml
- pyproject.toml
If you want to update and / or build the documentation, this PR is for you :)
> update the docs on building the documentation

- docs/api/bits.md
- docs/api/calibration.md
- docs/api/command.md
- docs/api/config.md
- docs/api/control.md
- docs/api/counter.md
- docs/api/decorators.md
- docs/api/exceptions.md
- docs/api/index.md
- docs/api/settings.md
- docs/api/setup.md
- libs/cgse-common/src/egse/bits.py
- libs/cgse-common/src/egse/calibration.py
- libs/cgse-common/src/egse/command.py
- libs/cgse-common/src/egse/config.py
- libs/cgse-common/src/egse/control.py
- libs/cgse-common/src/egse/counter.py
- libs/cgse-common/src/egse/decorators.py
- libs/cgse-common/src/egse/exceptions.py
- libs/cgse-common/src/egse/settings.py
- libs/cgse-common/src/egse/setup.py
- mkdocs.yml
- pyproject.toml
Added API documentation for the first batch of modules from the cgse-common module.
> first batch of API docs for cgse-common modules

- libs/cgse-common/src/egse/bits.py
fixed incorrect formatting of Args: in some functions
> fix Args: in docstring

- docs/api/device.md
- docs/api/dict.md
- docs/api/dummy.md
- docs/api/system.md
- docs/dev_guide/installation.md
- libs/cgse-common/src/egse/device.py
- libs/cgse-common/src/egse/dicts.py
- libs/cgse-common/src/egse/dummy.py
- libs/cgse-common/src/egse/system.py
- libs/cgse-common/tests/test_system.py
- mkdocs.yml
- pyproject.toml
Added API documentation for a second batch of modules in cgse-common. docstrings were updated accordingly.
> second batch of API docs for cgse-common modules

- docs/api/persistence.md
- docs/api/plugin.md
- docs/api/process.md
- libs/cgse-common/src/egse/persistence.py
- libs/cgse-common/src/egse/plugin.py
- libs/cgse-common/src/egse/process.py
- mkdocs.yml
Added more API docs from cgse-common
> another API doc update

- libs/cgse-common/src/egse/config.py
- libs/cgse-common/src/egse/process.py
- libs/cgse-common/tests/scripts/handle_sigterm.py
- libs/cgse-common/tests/scripts/process_with_children.py
- libs/cgse-common/tests/scripts/raise_value_error.py
- libs/cgse-common/tests/test_process.py
The `SubProcess` and related functions have been reworked and optimised.
* the subprocess is now not longer started with a 'shell' by default.
* a new function `list_zombies()` has been added 
* error checking has been improved
* the `reap_children()` has been reworked
* a method to check if the process is dead or a zombie has been added
* you can request the `exc_info` of the last exception in `execute()`
The unit test `test_process.py` has been extended.
> improvements to SubProcess

- libs/cgse-common/pyproject.toml
- libs/cgse-common/src/egse/calibration.py
- libs/cgse-common/src/egse/control.py
- libs/cgse-common/src/egse/dicts.py
- libs/cgse-common/src/egse/hk.py
- libs/cgse-common/src/egse/protocol.py
- libs/cgse-common/src/egse/setup.py
- libs/cgse-common/src/egse/state.py
- libs/cgse-common/src/egse/version.py
- libs/cgse-common/tests/test_command.py
- libs/cgse-common/tests/test_decorators.py
- libs/cgse-common/tests/test_resource.py
- libs/cgse-common/tests/test_setup.py
- libs/cgse-common/tests/test_system.py
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
The code contains fixes for issues found with `ruff check`. Tests were all green after changes. Patch version bump.
> Fix issues found with ruff check

- docs/dev_guide/project-configuration.md
- mkdocs.yml
See the developer guide → Project Configuration
> added some info docs on project configuration

- libs/cgse-common/src/egse/system.py
- libs/cgse-common/tests/test_system.py
- pyproject.toml
- AttributeDict now also prints label in repr()
- do_every() has an extra parameter count where you can restrict the number of iterations
- read_last_lines() now returns the lines without newline
- unit test has also been updated accordingly
> improvements to AttributeDict, do_every and read_last_lines in egse.system

- docs/roadmap.md
- libs/cgse-common/src/egse/command.py
- libs/cgse-common/tests/test_command.py
Some editorial changes for command sneaked in too :(
> Docs roadmap update

- libs/cgse-common/src/egse/command.py
- libs/cgse-common/tests/test_command.py
- noxfile.py
- projects/generic/keithley-tempcontrol/noxfile.py
- The load_commands() function is being refactored...
- Added the `nox` configuration
> maintenance on load_commands

- libs/cgse-common/src/egse/device.py
- libs/cgse-common/src/egse/scpi.py
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/keithley-tempcontrol/src/egse/tempcontrol/keithley/__init__.py
- projects/generic/keithley-tempcontrol/src/egse/tempcontrol/keithley/daq6510.py
- projects/generic/keithley-tempcontrol/src/egse/tempcontrol/keithley/daq6510_adev.py
- projects/generic/keithley-tempcontrol/src/egse/tempcontrol/keithley/daq6510_cs.py
- projects/generic/keithley-tempcontrol/src/egse/tempcontrol/keithley/daq6510_dev.py
- projects/generic/keithley-tempcontrol/src/egse/tempcontrol/keithley/daq6510_mon.py
- projects/generic/keithley-tempcontrol/src/egse/tempcontrol/keithley/daq6510_protocol.py
- projects/generic/keithley-tempcontrol/src/egse/tempcontrol/keithley/daq6510_sim.py
- projects/generic/keithley-tempcontrol/src/keithley_tempcontrol/cgse_services.py
- projects/generic/keithley-tempcontrol/src/keithley_tempcontrol/settings.yaml
- projects/generic/keithley-tempcontrol/tests/script_daq6510_mon.py
- projects/generic/keithley-tempcontrol/tests/test_adev.py
- projects/generic/keithley-tempcontrol/tests/test_dev.py
This pull request introduces asynchronous communication with devices with an initial example for the Keithley DAQ6510 multimeter. The basic commanding for the DAQ6510 is implemented through an asynchronous SCPI interface and tested with a script interacting with the monitor while it performs continuous polling of the device.
> asynchronous DAQ6510 interface and monitoring

- libs/cgse-common/pyproject.toml
- libs/cgse-common/src/egse/decorators.py
- libs/cgse-common/src/egse/system.py
- libs/cgse-common/tests/test_system.py
- libs/cgse-common/tests/test_task.py
This class can be used in an asynchronous environment. The callback doesn't need to be an async functions.
> Added a class Periodic which runs callback functions at given intervals

- libs/cgse-core/src/egse/confman/__init__.py
In my tests so far, the InfluxDB process was always running.  When this is not the case, writing to the client fails.  We now check for this explicitly.  If the InfluxDB process is started when the CM is already running, it picks up on this (i.e. the metrics start appearing in the database).
> Check whether InfluxDB is running before writing to client

- libs/cgse-core/src/egse/confman/__init__.py
> Added CGSE versions in CM HK/metrics

- projects/generic/cgse-tools/src/cgse_tools/cgse_commands.py
> init command no longer overwrites local settings file

- libs/cgse-core/src/cgse_core/settings.yaml
- libs/cgse-core/src/egse/storage/__init__.py
- libs/cgse-core/src/egse/storage/storage_cs.py
The sm_cs now uses dynamic port assignment and registers as a service.
> refactoring of the storage manager

- README.md
- libs/cgse-common/pyproject.toml
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/lakeshore-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
> cgse now installs core services by default.

- libs/cgse-common/src/egse/observer.py
- projects/generic/symetrie-hexapod/src/egse/hexapod/symetrie/hexapod_ui.py
The method names in the Observable class were not EP8 compliant and have been corrected.
> corrected the method names in Observable

- libs/cgse-core/tests/stress_test_registry_server.py
- pyproject.toml
Release the refactored registry server.
> Release/bump version 0.10.0

- libs/cgse-common/pyproject.toml
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/lakeshore-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
forgot to push all changed `pyproject.toml` files.
> bump version -> 0.10.0

- projects/generic/cgse-tools/src/cgse_tools/cgse_commands.py
We now have a additional `show` command:
```
$ cgse show setup
```
By default this command will get the current setup from the configuration manager and print it to the terminal.
> add `cgse show setup` command

- libs/cgse-common/pyproject.toml
- libs/cgse-common/src/egse/process.py
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/cgse-tools/src/cgse_tools/cgse_commands.py
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/lakeshore-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
An update in the regex pattern for matching Python commands.
> update a fix for `cgse show procs` and bumped version patch level

- libs/cgse-common/src/egse/signal.py
This pull request fixes issue #159.
> fix #159 - create signal_dir

- docs/libs/cgse-core/notifyhub.md
- libs/cgse-common/pyproject.toml
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-core/src/egse/control.py
- libs/cgse-core/src/egse/logger/__init__.py
- libs/cgse-core/src/egse/logger/log_cs.py
- libs/cgse-core/src/egse/notifyhub/__init__.py
- libs/cgse-core/src/egse/notifyhub/client.py
- libs/cgse-core/src/egse/notifyhub/server.py
- libs/cgse-core/src/egse/notifyhub/services.py
- libs/cgse-core/src/egse/registry/__init__.py
- libs/cgse-core/src/egse/registry/client.py
- libs/cgse-core/src/egse/registry/server.py
- libs/cgse-core/src/egse/storage/__init__.py
- libs/cgse-core/src/egse/storage/storage_cs.py
- libs/cgse-core/tests/script_subscribe_to_notifyhub.py
- libs/cgse-core/tests/test_event_notification.py
- libs/cgse-core/tests/test_notify_hub.py
- libs/cgse-gui/pyproject.toml
- mkdocs.yml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/lakeshore-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
This pull request
- adds the `status` command for the notification hub
- creates a `nh_cs` command (notification hub core service)
- fixes timing problem with termination of notification hub
> Feature status cmd for the notification hub

- docs/libs/cgse-core/notifyhub.md
- libs/cgse-common/pyproject.toml
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-core/src/egse/control.py
- libs/cgse-core/src/egse/logger/__init__.py
- libs/cgse-core/src/egse/logger/log_cs.py
- libs/cgse-core/src/egse/notifyhub/__init__.py
- libs/cgse-core/src/egse/notifyhub/client.py
- libs/cgse-core/src/egse/notifyhub/server.py
- libs/cgse-core/src/egse/notifyhub/services.py
- libs/cgse-core/src/egse/registry/__init__.py
- libs/cgse-core/src/egse/registry/client.py
- libs/cgse-core/src/egse/registry/server.py
- libs/cgse-core/src/egse/storage/__init__.py
- libs/cgse-core/src/egse/storage/storage_cs.py
- libs/cgse-core/tests/script_subscribe_to_notifyhub.py
- libs/cgse-core/tests/test_event_notification.py
- libs/cgse-core/tests/test_notify_hub.py
- libs/cgse-gui/pyproject.toml
- mkdocs.yml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/lakeshore-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
This pull request fixes one item in issue #173. The `log_cs` can now be started independent of other core services.
> log_cs now starts independent of other core services

- libs/cgse-common/pyproject.toml
- libs/cgse-common/src/egse/env.py
- libs/cgse-common/src/egse/system.py
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-core/src/cgse_core/services.py
- libs/cgse-core/src/cgse_core/settings.yaml
- libs/cgse-core/src/egse/logger/__init__.py
- libs/cgse-core/src/egse/logger/log_cs.py
- libs/cgse-core/src/egse/registry/backend.py
- libs/cgse-core/src/egse/registry/client.py
- libs/cgse-core/src/egse/registry/server.py
- libs/cgse-core/tests/fixtures/helpers.py
- libs/cgse-core/tests/test_registry_service.py
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/lakeshore-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
This pull request adds a `deregister` command to the `cgse registry` command. This is mainly an administration command as a help to solve registration problems for services. The command is:
```
$ cgse registry deregister <service type>
```
> add deregister command

- libs/cgse-common/pyproject.toml
- libs/cgse-common/src/egse/env.py
- libs/cgse-common/tests/test_env.py
- libs/cgse-coordinates/pyproject.toml
- libs/cgse-core/pyproject.toml
- libs/cgse-core/src/cgse_core/_start.py
- libs/cgse-core/src/cgse_core/_stop.py
- libs/cgse-core/src/cgse_core/services.py
- libs/cgse-core/src/cgse_core/settings.yaml
- libs/cgse-core/src/egse/connect.py
- libs/cgse-core/src/egse/notifyhub/__init__.py
- libs/cgse-core/src/egse/storage/storage_cs.py
- libs/cgse-gui/pyproject.toml
- projects/generic/cgse-tools/pyproject.toml
- projects/generic/keithley-tempcontrol/pyproject.toml
- projects/generic/lakeshore-tempcontrol/pyproject.toml
- projects/generic/symetrie-hexapod/pyproject.toml
- projects/plato/plato-fits/pyproject.toml
- projects/plato/plato-hdf5/pyproject.toml
- projects/plato/plato-spw/pyproject.toml
- pyproject.toml
This pull request addresses some maintenance updates to logging.
> Maintenance logging
